name: FairyChat
version: '${version}'
main: de.rexlmanu.fairychat.plugin.FairyChatPlugin
loader: de.rexlmanu.fairychat.plugin.FairyChatLoader
description: ${description}
api-version: '1.19'
folia-supported: true
website: https://github.com/rexlManu/FairyChat
dependencies:
  - name: MiniPlaceholders
    required: true
  - name: LuckPerms
    required: false
