[versions]
minecraft = "1.19.4-R0.1-SNAPSHOT"
[plugins]
userdev = { id = "io.papermc.paperweight.userdev", version = "1.5.5" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.1.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
lombok = { id = "io.freefair.lombok", version = "6.6.1" }
[libraries]
annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }
jedis = { module = "redis.clients:jedis", version = "4.1.1" }
miniplaceholders = { module = "io.github.miniplaceholders:miniplaceholders-api", version = "2.1.0" }
commandframework = { module = "cloud.commandframework:cloud-paper", version = "1.8.3" }
configlib = { module = "com.github.Exlll.ConfigLib:configlib-paper", version = "v4.2.0" }
guice = { module = "com.google.inject:guice", version = "7.0.0" }
luckperms = { module = "net.luckperms:api", version = "5.4" }